### ISSUE TITLE
Shadow published_date with updated_date where applicable

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-nist#111]
All instances of published date on cover pages of NIST needs to be accompanied by either "(including updates as of xxx)" or "(updated xxx)"; presumably the former.

**Comment by ronaldtse** [comment]
Confirmed: "(including updates as of xxx)" is officially correct. 

On the other hand, the `published_date` in NIST SP seems to be an `edition`, not an actual date. There are other NIST publications that use a full YYYY-MM-DD publication date.

I'm seeking clarification here.

**Comment by opoudjis** [comment]
I don't even understand the distinction you're making, so I will wait.

**Comment by ronaldtse** [comment]
Question on NIST publication dates:

* Publication date is "Month Year" (for NIST SP), but "Month Day, Year" (for other NIST)
* Release date is "Month Day, Year" 

The point is both dates are required and must coexist.

How do we realize them in metadata?

Option 1. To me, the "Publication Date" is not the actual "date of publication" since there's no year. In ISO, we use `copyright-year` to model the year, and `edition` to indicate the edition number. This is similar to in NIST SP where "Month Year" is like copyright year, and "Revision" is done using `edition`. Is this approach correct? Should we extend `copyright-year` to `copyright-date` to support this?

Option 2. Change `publication-date` to support month-year in addition to the full date.

The "Release date" of "Month Day, Year" can be realized with "issue-date" or "publication-date"?

**Comment by opoudjis** [comment]
Publication date can support Month Year as well as full date in rendering: *all* dates are output to template in the three formats MMM DD, YYYY; MM-DD-YYYY; and MMM YYYY.

There is going to be difficulty in specifying a date with Month and Year only, since that is not a legal Ruby date (https://github.com/metanorma/isodoc/issues/90). If you specify a day, it will obviously be ignored in the MMM YYYY output anyway.

You've already requested in another ticket, #115, that published-date be replaced with issued-date, whereupon the release date becomes published-date. You've also indicated that the released date does not actually appear in the current documents, and is metadata only.

**Comment by opoudjis** [comment]
This has already been implemented on the title page as "Includes updates as of {{}}", in #93. 

I am adding the update date to the authority statement in the format given here, shoving it inside the parentheses:

````
  Natl. Inst. Stand. Technol. {{ docidentifier_undated | remove: "NIST " | replace: " Volume ", " Vol. " }}, ({{ most_recent_date_monthyear }}{% if updateddate_mmddyyyy %}, including updates as of {{updateddate_mmddyyyy}}{% endif %}) 
````

I am adding update dates to published dates for superseding documents, in the format given.
