### ISSUE TITLE
References should be rendered with label in the beginning

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#130]
References should be rendered with label in the *beginning*. See this rendering from the `mn-templates-nist`.

<img width="672" alt="Screen Shot 2019-06-19 at 1 53 39 AM" src="https://user-images.githubusercontent.com/11865/59707428-2e58bc00-9235-11e9-9385-fb442ef16c77.png">

**Comment by opoudjis** [comment]
What are you calling the label here? "Security techniques"?

**Comment by ronaldtse** [comment]
I meant the references from the second onwards.

**Comment by ronaldtse** [comment]
P.S. this is a regression, it used to work. We need a test for this.

**Comment by opoudjis** [comment]
I'm sorry, I still do not understand what you are talking about. Please give the source, and what this should be rendering as.

**Comment by opoudjis** [comment]
Right.

https://github.com/metanorma/metanorma-nist/issues/110 has NOT BEEN IMPLEMENTED YET, so for you to expect its behaviour to be already in place is unreasonable. You were meant to be confirming whether numeric references were still required.

The currently implemented behaviour is to append any document identifiers after the formatted reference, because that was what was found in the sample documents. I am reluctantly going to change the code so that the identifier is prefixed if it is `[\d+\]`, and suffixed otherwise; that will mean that users will need to inject numbers rather than document identifiers, and preformatted references, if they want numeric references.
