### ISSUE TITLE
SP 800-90B document math equations shows broken font

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#154]
This is shown in a number of places but here's an example of the "unrenderable character square".

<img width="592" alt="image" src="https://user-images.githubusercontent.com/11865/66868733-2d932500-ef9e-11e9-9470-c541ec7559f4.png">

6.3.2 g) as well:

<img width="552" alt="image" src="https://user-images.githubusercontent.com/11865/66868813-587d7900-ef9e-11e9-8487-46020b27cd6f.png">

**Comment by opoudjis** [comment]
Yes, that is a longstanding problem to do with the MathML to OOXML mapping, and we did fix some instances of it by getting rid of spaces, but it is far from clear to me how I am going to fix this.

**Comment by opoudjis** [comment]
For the example 

````
[stem]
++++
2w = lambda/pi [ (2 int_0^(pi/2) F^2(theta) sin theta cos theta d theta) / (int_0^(pi/2) F^2(theta)sin^3 theta cos theta d theta)]^(1/2)
++++
````

we are getting a black square between the integral of `2 int_0^(pi/2)` and the argument of `F^2(theta) sin theta cos theta d theta`. The integral is expecting a single argument, and is not finding it. If we wrap the integral argument in `{:`, it renders correctly:

````
[stem]
++++
2w = lambda/pi [ (2 int_0^(pi/2) {:F^2(theta) sin theta cos theta d theta:}) / (int_0^(pi/2) {:F^2(theta)sin^3 theta cos theta d theta:})]^(1/2)
++++
````

This is in fact an early finding we made with the asciimath gem, but which is being reconfirmed here: the Asciimath parser is pretty strict, and requires a lot more bracketing than Asciimath that is to be processed by MathJax. This may be seen as a bug, but I'm not sure how to mitigate it.

**Comment by opoudjis** [comment]
I'm surprised that this even applies to:

````
[stem]
++++
bar X' = (1)/(v) sum_(i = 1)^(v) {:t_(i):}
++++
````

requiring t_(i) to be wrapped as a single expression. But it does.

**Comment by opoudjis** [comment]
Documented in metanorma.com

**Comment by opoudjis** [comment]
Bracketing is addressing many of the blank square issues, but not all of them, including the Sum example.

**Comment by opoudjis** [comment]
Digging into the XSL; 

https://www.unicode.org/notes/tn28/UTN28-PlainTextMath-v3.1.pdf documents the Word competitor to AsciiMath (because fucking Microsoft): sums are explicitly tied to summands as operands through the \naryand or \of operator, U+2592. if that operand is missing, Word complains, and puts up a dotted square.

For reasons I cannot work out, `sum_(i=1)^n i^3` processes correctly in Word, and `sum_(i=1)^n i` does not. However, I have worked out the guilty assumption in the Word stylesheet:

````
MathML doesn't have the concept of nAry structures.  The best approximation
       to these is to have some under/over or sub/sup followed by an mrow or mstyle.
````

It appears that Word expects the operand of a nary operator (i.e. any munder, mover, munderover, msub, msup, msubsup) to be an mrow. Of course, operands are typically just mi or mo or whatever else; they are not recognised as such, so the nary operator ends up with no argument in the OOXML.

I am electing to fix this issue in our local, prerelease stylesheet.

**Comment by opoudjis** [comment]
Actually, it's too difficult to fix in the stylesheet, given that the condition on when these kinds of expressions are operators is calculated and not in an XPath. I will simply wrap the next element after a munder etc. in an mrow. (This is what the {: :} solution for other instances of dotted square anticipates; it's just that {: :} gives mfenced, not mrow.)

**Comment by opoudjis** [comment]
It turns out I had emended this behaviour a very long time ago for munderover + msup; this is generalising this one-off fix.
