### ISSUE TITLE
Math syntax "min" and "log" are displayed as variables rather than functions in Word

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#155]
In HTML, the math keywords "min" "log" are correctly shown as function names (non-italicized):

(this is in "SP 800-90B 6.3.2 h)")

<img width="470" alt="image" src="https://user-images.githubusercontent.com/11865/66869013-c32eb480-ef9e-11e9-937e-536379cbfc0d.png">

But in Word these keywords are showed as variables:

<img width="602" alt="Screen Shot 2019-10-15 at 10 54 42 PM" src="https://user-images.githubusercontent.com/11865/66869033-c9249580-ef9e-11e9-9dfc-54f7b1ef59dd.png">

**Comment by opoudjis** [comment]
If OOXML does not understand default italicisation of functions like MathML does, well, we're screwed, aren't we. MathML to OOXML conversion will have to start introducing idiosyncratic italicisation, and we already know that OOXML will only accept it as HTML markup.

**Comment by opoudjis** [comment]
The MathML is indeed correctly treating `min` as an operator, tagged in `<mo>`.

MathML says that mo (operator) and mn (number) defaults to normal, while mi (variable) is normal if multiple characters, but italic if a single character.

The Word XSLT does NOT implement this: it has:

````
<xsl:when test="$ndCur/self::mml:mi and (string-length(normalize-space($ndCur)) &lt;= 1)               or $ndCur/self::mml:mn and string(number($ndCur/text()))!='NaN'               or $ndCur/self::mml:mo">

           <!-- The default for the above three cases is fontstyle=italic fontweight=normal.-->
````

Meaning that it has the correct behaviour for mi, but incorrect behaviour for numbers (though I haven't seen it actually happen) and for mo.

I am going to correct the Word XSLT stylesheet to not italicise operators.

**Comment by ronaldtse** [comment]
Thanks @opoudjis for the investigation, perhaps we should maintain this XSLT in a separate repo too.

**Comment by opoudjis** [comment]
No, that's not made a difference. It's possible that the formatting instructions in OOXML are not being output in the right place:

`<m:r><m:rPr><m:sty m:val="p"></m:sty></m:rPr><m:t>log</m:t></m:r>`

The `<m:sty m:val="p">` is expressly an instruction to use normal type for _log_; but it is being ignored in Word.

It turns out that Word needs an additional `<m:scr m:val="roman"/>` to accompany normal font; the Word XSLT adds m:scr to most font shifts, but not to normal.

That is not the issue either though: the issue is that the entire expression is wrapped in a `<span class=stem>`, which has a default italics. This is in fact presupposed by the OOXML. But the normal style commands are failing to override it on their own: saved Word seems to need to introduce a `<span style='font-style:normal'>` wrapper to do so, around the `<m:r>` wrapper of formatted maths.

**Comment by opoudjis** [comment]
So: for whatever reason, the default italic of math expressions in Word is NOT being overridden by style commands in OOXML; it is only overridden in OOXML `<m:t>` (text)—so it is overridden by tag. In order to override the default italic, we need to wrap  `<span style='font-style:normal'>` around `m:r[m:Pr/m:sty[m:val='p']]`. We would presumably need to do this for all formatted maths, and that would explain past failure of boldface to appear.

**Comment by opoudjis** [comment]
Am investigating font commands in MathML, like `<mstyle mathvariant="bold"><mtext>AA</mtext></mstyle>`, which are being ignored by OOXML...

**Comment by opoudjis** [comment]
mstyle attributes are being ignored (other than colour) in XSLT: it is only using the mstyle attribute of the current tag. Will read ancestor mstyle mathvariant attribute if unpopulated.

**Comment by opoudjis** [comment]
Even with that done, `m:sty` is being ignored by Word, and I will need to wrap it with span as well. 

Will do:

* fonts: b, p (normal), bi

For now, at least, I am not doing font switches (Fraktur, Sans-Serif, Script, Monoscape, Double-Struck): we would need guaranteed fonts for those, or alternatively, canonical mapping to Mathematical Plane 1 symbols.

**Comment by opoudjis** [comment]
> Thanks @opoudjis for the investigation, perhaps we should maintain this XSLT in a separate repo too.

Maybe, but I don't see the need right now.
