### ISSUE TITLE
docidentifier `nist-mr` still broken

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#167]
In `mn-samples-nist`:

```xml
<uri type="doi">https://doi.org/10.6028/NIST.CWSP.01262018</uri>
<docidentifier type="NIST">NIST CSWP 01262018</docidentifier>
<docidentifier type="nist-long">NIST Cybersecurity White Paper 01262018</docidentifier>
<docidentifier type="nist-mr">NIST.CSWP.01262018...</docidentifier>
```

```xml
<uri type="doi">https://doi.org/10.6028/NIST.SP.800-116r1</uri>
<docidentifier type="NIST">NIST SP 800-116 Revision 1</docidentifier>
<docidentifier type="nist-long">NIST Special Publication 800-116 Revision 1</docidentifier>
<docidentifier type="nist-mr">NIST.SP.800-116..1.</docidentifier>
```

Please add a proper spec to ensure this issue remains resolved. Thanks.

**Comment by opoudjis** [comment]
> Please add a proper spec to ensure this issue remains resolved

The spec is fine, and there is only one issue with markup of a document. Inasmuch as this ID has space for volumes, revisions, and draft update dates, it is constantly going to have missing components in it by design. 

````
"NIST.#{name}.#{args[:id]}.#{args[:vol]}.#{args[:revision]}.#{args[:date]}"
````

NIST CSWP 01262018 has:
* no volume
* no revision (the date is already the identifier anyway)
* no updated-date because of typo in source; fixed. (The date is updated date or circulated date, but not issued/published date, which is assumed by default.)

NIST SP 800-116 Revision 1 has:

* no volume
* no updated date (the issued date refers already to the revision).

**Comment by ronaldtse** [comment]
The fact is the `nist-mr` scheme is not defined:

* NIST CSWP will not have volume
* NIST SP may not have volume

The `nist-mr` scheme should be a structured identifier that allows machine reading. Or it directly implements the PubID or the DOI scheme.

**Comment by opoudjis** [comment]
I have a definition, which you supplied: `"NIST.#{name}.#{args[:id]}.#{args[:vol]}.#{args[:revision]}.#{args[:date]}"`. 

If you now don't like that definition, well, that's what #168 is for.
