### ISSUE TITLE
Copyright symbol and (c) generation

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-nist#197]
Both `(C)` and `(c)` are producing copyright symbol in Metanorma. In AsciiDoctor, I was able to find that only `(C)` produces this symbol.
When writing `\(C)` in .adoc, expected result is produced, i.e. `(C)`. However, backslash is generated in DOC/PDF in case of writing `\(c)` in .adoc and I wasn't able to find the proper way to generate `(c)` instead of the copyright symbol.

Example which illustrates this issue is attached.
[test_copyright.zip](https://github.com/metanorma/mn-samples-nist/files/4511694/test_copyright.zip)

**Comment by opoudjis** [comment]
The difference betweeen Asciisdoctor and Metanorma is because I repair these expansions using the gem sterile (for smart quotes), and sterile also has a more liberal set of symbols. 

My generic advice to @manuel489 from yesterday, https://github.com/metanorma/metanorma-standoc/issues/263, also applies here. If you want to prevent a combination of two or more characters from being converted to a single symbol, don't use backslash, which is completely at the mercy of what Asciidoctor has implemented. Instead, interrupt the sequence using the Zero Width Non Join character, U+200C. So in this case:

`(&#x200c;c)`

**Comment by opoudjis** [comment]
Btw, thank you for not assigning me this ticket. I have been genuinely overwhelmed.

**Comment by ronaldtse** [comment]
@anermina can you add this to a FAQ section on metanorma.com ? Thanks
