### ISSUE TITLE
Missing "Reports on Computer Systems Technology" statement

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#69]
>  "Reports on Computer Systems Technology" statement (see official PDF) must appear before the Abstract. Different statement, depending on publication series.

This screenshot is from the authoritative PDF: 
https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-116r1.pdf

<img width="989" alt="Screen Shot 2019-03-17 at 2 16 05 PM" src="https://user-images.githubusercontent.com/11865/54486165-37955e00-48bf-11e9-96fa-48b0e16abd07.png">

We probably should make this a `[preface]` section and let the user specify, just like the Foreword.

**Comment by opoudjis** [comment]
That's not enough. The unique placement of this section in front of the abstract needs that it needs to be labelled explicitly as a distinct semantic element; its title is going to change for each publication series, so it alone does not help the section be recognised.

In truth, I think this is just a foreword. It plays the same role as ISO forewords, and we have not seen forewords in NIST documents otherwise. I will be recommending that they be marked up in that fashion.

**Comment by opoudjis** [comment]
To make this work, am allowing Forewords to have user-specified titles in metanorma-standoc.
