### ISSUE TITLE
Bibliography is always called "References"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#70]
>  "Bibliography" -- Rename to "References" when this is rendered, regardless of the output format.

**Comment by opoudjis** [comment]
This is going to get rescinded, I can just feel it, but ok.

**Comment by ronaldtse** [comment]
@opoudjis you mean by NIST in the future?

**Comment by opoudjis** [comment]
Yes. Didn't they explicitly ask for Normative References to be differentiated from others?

**Comment by ronaldtse** [comment]
I thought they don't differentiate them now? It may be the case they differentiate them in the future.

**Comment by opoudjis** [comment]
https://github.com/metanorma/metanorma-nist/issues/47

**Comment by opoudjis** [comment]
NIST have already requested one legacy support feature, arbitrary positioning of bibliographies. I have zero reason to trust them not to request more.

**Comment by opoudjis** [comment]
I've implemented this, but think it is a mistake to.

**Comment by ronaldtse** [comment]
Thanks. Can we keep a list of things that NIST should consider fixing?

**Comment by opoudjis** [comment]
You can :-) But you have just given them a long list of things to respond to; this is a continuation of that dialogue. (But that dialogue cannot continue for very long, for reasons I'd rather not reiterate.) Do impress on them that they cannot keep changing their mind on whether to support legacy features or not: we need clear guidance on the status of legacy features.

Right now, if there are two references sections, one Normative and one Informative, they will have the identical title. Because that's what they've asked for, forgetting that they also asked for #47.

**Comment by ronaldtse** [comment]
I think for #47 they want to "allow" 2 separate bibliographies for new documents, but for backwards compatibility, they need a way to have a single bibliography.

**Comment by opoudjis** [comment]
... I repeat. Right now, if they have two separate bibliographies, they will get the same title, "References", because that's what this ticket asks for. If #47 is a valid requirement, then this ticket must not be implemented.

**Comment by ronaldtse** [comment]
Hmmm. I think we can still have:

* Single one: "References"
* Two: "Normative references", "References"
?

**Comment by opoudjis** [comment]
Fine.

This is going to end, right?

**Comment by ronaldtse** [comment]
We should be able to reach a steady state soon :-)
