### ISSUE TITLE
XML: encode Authority section

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#76]
> Authority section needed.

The Authority section should be encoded in the XML. In fact, all the boilerplate text should be encoded in the XML so that an older standard can be represented without change using a newer versioned Metanorma processor.

This needs some further generalization for the entire Metanorma series.

**Comment by opoudjis** [comment]
It is unacceptable to encode the idiosyncratic boxes and font shifts of the following as semantic XML: they have no business there, and Metanorma is not Microsoft Word.

<img width="498" alt="image" src="https://user-images.githubusercontent.com/1911039/54751614-9ba58280-4c2f-11e9-9a20-1220c0418fd3.png">

If we semantically mark up the authority statement instead, then we need to have a separate element for each of the four segments of the page. And we have no guarantee that those segments will not change between iterations. 

Incorporating heavily marked up boilerplate into the XML is the wrong solution to this problem. The correct solution for legacy documents is to provide legacy boilerplate pages, which can be used instead of the current boilerplate page. (Recall that the html_*_intro.html and word_*_intro.html pages can be set as document attributes.)

**Comment by opoudjis** [comment]
This is a brutal refactoring, and I am going to limit myself to the authority statement. It will be managed as a Liquid template. I will need to get it rendered at all out of XML, before I can contemplate making it customisable.

**Comment by opoudjis** [comment]
The authority statement has been moved to lib/asciidoctor/nist/nist_intro.xml, as Metanorma XML, out of the HTML of word_nist_intro.html and html_nist_intro.html. I will add a `:boilerplate-authority:` option to read it in from a user nominated file.

In other gems, boilerplate may be simple enough to leave as Asciidoctor. I think it complicated enough in this instance that it should be left in Metanorma XML.

**Comment by ronaldtse** [comment]
@opoudjis could you also let add documentation on how to customize the authority section? Thanks!

**Comment by opoudjis** [comment]
Done
