### ISSUE TITLE
Department of Commerce logo and official names should be on the same page

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#87]
Self explanatory:

<img width="586" alt="image" src="https://user-images.githubusercontent.com/11865/55536285-f210c780-56eb-11e9-8bbb-d5e94c739dd0.png">

**Comment by opoudjis** [comment]
I do not want to do this.

If they put a shit-ton of names on the front page, the page is going to overflow. They get around that by ad hoc formatting such as columns. I might be persuaded to put the names and affiliations into two columns by default. But in the general case, there is no way to guarantee that the data won't overflow.

**Comment by ronaldtse** [comment]
I think these elements must be placed in a fixed text box location. The authors must be put in a text box as well to ensure they don't overflow.

**Comment by opoudjis** [comment]
That's not a solution at all. If you put too much text in a fixed text box, it merely truncates.

**Comment by ronaldtse** [comment]
> fixed text box, it merely truncates

At least it doesn't shift the other elements, that's an improvement 😉

**Comment by opoudjis** [comment]
It's truncating the text. It is decidedly not an improvement.

**Comment by ronaldtse** [comment]
Wait, truncating which text?

**Comment by opoudjis** [comment]
The text of the author listing that would go in the fixed box, if you put a long enough list.

Please just let me do two columns.

**Comment by opoudjis** [comment]
... No, you're right. This will have to be fixed text after all, because of the footer position.

I was sick of this a month ago.

**Comment by opoudjis** [comment]
No, I'm not doing a textbox. The beginning of the text box is unpredictable, because the title may have arbitrarily many lines. And textboxes are going to truncate overflowing text. No.

I am going to make the logo fixed to the end of the page, as is already happening with the logo on the previous two pages. That will guarantee that the logo will not overflow. In the process, that gets rid of the carriage returns that have been used already to pad out the page. That will buy you four more lines. 

And if there are too many authors, Oh well, they can good and manually intervene.

I can't make the author text two columns in the general case, because if there is a small amount of author text, it will end up on the left hand column only.

Do not insist on this, @ronaldtse. This is not TeX, and I am wasting much too much time already on formatting that will necessarily end up being done by hand anyway.

**Comment by opoudjis** [comment]
... Actually putting the information shown in a textbox, instead of the authors, is as good a solution as we're going to get: if there's no room on the page, the information shown is pushed onto the next page. Unfortunately that happens in 800-116: there are two lines of authors too many. I'm going to try and shave space to mitigate that, but it's only ever going to be a mitigation.

**Comment by opoudjis** [comment]
It's an intractable problem in the general case, but I think I've bought as much space as I can, and if there is a much longer list of authors, there will need to be postediting and two columns.
