### ISSUE TITLE
Support "[Review] Amend" stage in NIST pub (adding Errata)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#93]
Erratas can be added in two stages:

1. Right after publishing
2. From the NIST ERB 5-year review process

A document of such state will be modified to include an errata message on the TITLE PAGE, right under the "date" (right aligned, of course):

<img width="504" alt="PastedGraphic-3" src="https://user-images.githubusercontent.com/11865/55644123-858aeb00-5807-11e9-974c-b9a8ebb22062.png">

The document is considered changed because of the Errata. All other details of the document remain identical (including document identifier, revision number).

In this situation, a new "draft-final" document will be created.

This also means that the "revision date" should be entered as a document attribute and added to the bibliographic dates.

This task is to implement the Errata message, which also provides a linkage directly to the Errata section.

**Comment by opoudjis** [comment]
See Page IX.

I am going to attempt to do this in the Word document, swearing bitterly all the time while doing it. If I succeed, they are likely going to have to update the errata page reference manually, just as they do with tables of contents. DO NOT ASK ME TO WORK AROUND THAT; I will not start injecting unreliable VBA into Word. If I fail, again, DO NOT ASK ME TO PERSIST.

Better in fact you not ask for this at all. METANORMA IS NOT MICROSOFT WORD. And I have resented for months that they assume that it can be.

**Comment by opoudjis** [comment]
> In this situation, a new "draft-final" document will be created.

There is no such thing as "draft-final". Indicate what this is supposed to be.

I will be detecting the presence of an errata table and generating the message if it is there. The revision date is an attribute of bibdata/version, and has deliberately been kept separate from the suite of bibliographic dates. I will not be adding it to the bibliographic dates, and that is not the date you need here anyway. The bibliographic date which should be associated with this is updated-date.

Yes, another date  for NIST to keep track of. 

The "linkage directly to the Errata section" might be possible as a hyperlink; inserting dynamic page numbers in Word HTML is very unlikely to work.

**Comment by opoudjis** [comment]
Added "Includes Updates as of updated-date" message.

**Comment by opoudjis** [comment]
Well, that's annoying. After all that, it looks like the errata page ref will be relatively easy to add. (I just wasn't familiar with that functionality in Word.)

**Comment by opoudjis** [comment]
Page number works; but of course page number requires updating of fields.

And because this page number is now in a text box, thanks to #87, if I select the whole document and update fields (https://support.office.com/en-us/article/create-or-update-a-cross-reference-aa35c606-34e8-4c64-b6eb-c6321d190645), the page reference is not updated: you need to select and update the page reference field within the text box separately.

In fact, if I select the entire contents of the text box, and do Ctrl-opt-shift-U, the logo doubles in size and disappears, and the textbox becomes too big to fit on one page, and skips to the next page. The only way i can update it is by selecting the specific page number, and updating field on just that.

At this stage, I no longer give a crap about Word's UI. If NIST have been inserting these cross-references in Word already, they can continue to update them in Word output as they always have.

**Comment by opoudjis** [comment]
From https://github.com/metanorma/metanorma-nist/issues/101, I have made the melancholy discovery that the update date is at least sometimes appended after the published date, where available. Encourage NIST to identify such instances in testing; I have no idea how widespread that should be, especially in citations.
